name: Hello

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - development

permissions:
  contents: read

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - run: echo "Hello Friend"